micronaut:
  application:
    name: mn06
  session:
    http:
      cookie: true
      header: true
netty:
  default:
    allocator:
      max-order: 3

tracing:
  zipkin:
    http:
      url: http://host.docker.internal:9411
    enabled: true
    sampler:
      probability: 1

hello:
  world:
    message: "Hello message!"
goodbye:
  world:
    message: "Goodbye message!"

