micronaut:
  application:
    name: mn06
  session:
    http:
      cookie: true
      header: true
netty:
  default:
    allocator:
      max-order: 3

hello:
  world:
    message: "Hello message!"
goodbye:
  world:
    message: "Goodbye message!"

